/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wheresmybus;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author gastonmugas
 */
public class NewJFrame extends javax.swing.JFrame {

    XLSParser parser = new XLSParser();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        PanelHora.setVisible(false);
        LabelHora.setVisible(false);
        LabelMinutos.setVisible(false);
        LabelSiguiente.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboLine = new javax.swing.JComboBox<>();
        jComboStop = new javax.swing.JComboBox<>();
        jComboDirection = new javax.swing.JComboBox<>();
        LabelMinutos = new javax.swing.JLabel();
        LabelSiguiente = new javax.swing.JLabel();
        PanelHora = new java.awt.Panel();
        LabelHora = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboLine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linea", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "60", "61", "62", "63", "64", "65", "66", "67", "68" }));
        jComboLine.setToolTipText("Seleccione la Linea que desea consultar");
        jComboLine.setEnabled(jComboStop.isEnabled());
        jComboLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboLineMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboLineMouseClicked(evt);
            }
        });
        jComboLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboLineActionPerformed(evt);
            }
        });

        jComboStop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parada", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboStop.setToolTipText("Seleccione la parada para consultar");
        jComboStop.setEnabled(false);
        jComboStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboStopMouseClicked(evt);
            }
        });
        jComboStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboStopActionPerformed(evt);
            }
        });

        jComboDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direccion", "1", "2" }));
        jComboDirection.setToolTipText("Seleccione en que direccion va el colectivo");
        jComboDirection.setEnabled(false);
        jComboDirection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboDirectionMouseClicked(evt);
            }
        });
        jComboDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDirectionActionPerformed(evt);
            }
        });

        LabelSiguiente.setText("dsdfdsfds");

        PanelHora.setBackground(new java.awt.Color(255, 255, 255));

        LabelHora.setBackground(new java.awt.Color(255, 255, 255));
        LabelHora.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 75)); // NOI18N
        LabelHora.setText("15:45");

        javax.swing.GroupLayout PanelHoraLayout = new javax.swing.GroupLayout(PanelHora);
        PanelHora.setLayout(PanelHoraLayout);
        PanelHoraLayout.setHorizontalGroup(
            PanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHoraLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(LabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        PanelHoraLayout.setVerticalGroup(
            PanelHoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHoraLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wheresmybus/bondi4.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelMinutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboLine, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboStop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelSiguiente)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboLineMouseClicked
        jComboDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direccion"}));
        jComboDirection.setEnabled(false);
        
        jComboStop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parada"}));
        jComboStop.setEnabled(false);        
        LabelHora.setVisible(false);
        LabelMinutos.setVisible(false);
        LabelSiguiente.setVisible(false);
        PanelHora.setVisible(false);
        
    }//GEN-LAST:event_jComboLineMouseClicked

    private void jComboStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboStopActionPerformed
      
            
        try {
            // Set stop
            String stopName = (String) jComboStop.getSelectedItem();
            parser.SetStopName(stopName);
            parser.SetStopNumber();
          
            parser.read2();
                    
            // Search for the closest bus times
            parser.GetCurrentTime();
            parser.GetClosestTime();
            parser.GetNextClosestTime(); 
            
            // Print results
            PanelHora.setVisible(true);
            LabelHora.setText(parser.UpcomingBusTime());
            LabelHora.setVisible(true);
            LabelMinutos.setText(parser.NextBusDiff());
            LabelMinutos.setVisible(true);
            LabelSiguiente.setText(parser.NextBusTime());
            LabelSiguiente.setVisible(true);
            
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           
    }//GEN-LAST:event_jComboStopActionPerformed

    private void jComboLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboLineActionPerformed
            
            PanelHora.setVisible(false);
            LabelHora.setVisible(false);
            LabelMinutos.setVisible(false);
            LabelSiguiente.setVisible(false);
            //Get Line
            jComboStop.setEnabled(false);

            Object selected = jComboLine.getSelectedItem();
            if ( selected == "Linea")
            {
            jComboDirection.setEnabled(false);
            }
            else {
                try {
                    int line = Integer.valueOf((String) selected);
                    parser.SetLine(line);
                    parser.SetInputFile();
                    
                    parser.read3();
                    final DefaultComboBoxModel directions = new DefaultComboBoxModel(parser.directionList);
                    jComboDirection.setModel(directions);
                    
                    jComboDirection.setEnabled(true);
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

    }//GEN-LAST:event_jComboLineActionPerformed

    private void jComboLineMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboLineMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboLineMousePressed

    private void jComboDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDirectionActionPerformed
        try {
            // Get direction
            
            String selected = (String) jComboDirection.getSelectedItem();
            if ( selected == "Direccion")
            {
            jComboStop.setEnabled(false);
            LabelMinutos.setVisible(false);
            LabelHora.setVisible(false);
            LabelSiguiente.setVisible(false);
            PanelHora.setVisible(false);
            }
            else{
            parser.SetDirectionName(selected);
            parser.SetDirectionNumber();
            parser.read();
            parser.GetStopList();
            final DefaultComboBoxModel stops = new DefaultComboBoxModel(parser.stopList);
            jComboStop.setModel(stops);
            jComboStop.setEnabled(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jComboDirectionActionPerformed

    private void jComboDirectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboDirectionMouseClicked
        jComboStop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parada"}));
        jComboStop.setEnabled(false);
      
        LabelHora.setVisible(false);
        LabelMinutos.setVisible(false);
        LabelSiguiente.setVisible(false);
        PanelHora.setVisible(false);
    }//GEN-LAST:event_jComboDirectionMouseClicked

    private void jComboStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboStopMouseClicked
        LabelHora.setVisible(false);
        LabelMinutos.setVisible(false);
        LabelSiguiente.setVisible(false);
        PanelHora.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jComboStopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelHora;
    private javax.swing.JLabel LabelMinutos;
    private javax.swing.JLabel LabelSiguiente;
    private java.awt.Panel PanelHora;
    private javax.swing.JComboBox<String> jComboDirection;
    private javax.swing.JComboBox<String> jComboLine;
    private javax.swing.JComboBox<String> jComboStop;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
