source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'page-object'
gem 'data_magic'
gem 'fig_newton'
gem 'ruby-gmail'
gem 'mail'
gem 'nokogiri'
gem 'os'
gem 'api-auth'
gem 'rest-client'
gem 'json-compare'
gem 'yajl-ruby'
gem 'rspec-expectations'
gem 'syntax'
gem 'watir-scroll'
gem 'addressable'
gem 'htmlentities'




